steps:
  - name: 'node:20'
    dir: 'Customer'
    entrypoint: 'bash'
    args:
      - -c
      - npm ci && npm run build

  - name: 'node:20'
    dir: 'Hotel'
    entrypoint: 'bash'
    args:
      - -c
      - npm ci && npm run build

  - name: 'node:20'
    dir: 'Admin'
    entrypoint: 'bash'
    args:
      - -c
      - npm ci && npm run build

options:
  logging: CLOUD_LOGGING_ONLY
